# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-08-15 09:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='books',
            name='book_name',
        ),
    ]
