# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-08-15 12:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_remove_books_book_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='book_name',
            field=models.CharField(default='The abandon', max_length=25),
        ),
    ]
